### ISSUE TITLE
Script does not start correctly.

### ISSUE THREAD

**Issue by boxy-boy** [ahmanwoods/Oculus-Defibrillator#4]
On start, i get the following.

`Error operating on sqlite database. Please fully restart your Oculus client and try again.
Traceback (most recent call last):
  File "C:\Users\Johnny\Downloads\Oculus-Defibrillator-master\oculus_heartbeat.py", line 75, in <module>
    main()
  File "C:\Users\Johnny\Downloads\Oculus-Defibrillator-master\oculus_heartbeat.py", line 52, in main
    oauth = get_oauth_token()
  File "C:\Users\Johnny\Downloads\Oculus-Defibrillator-master\oculus_heartbeat.py", line 17, in get_oauth_token
    for row in cur.execute("SELECT * FROM 'Objects' WHERE hashkey = '__OAF_OFFLINE_DATA_KEY__'"):
sqlite3.OperationalError: no such table: Objects
`
Help?

**Comment by ahmanwoods** [comment]
Did you fully close and restart your oculus client?

**Comment by boxy-boy** [comment]
Buncha times. I even restarted my computer.
After mucking around a bit i accidentally discovered that multiplayer games work fine without the script? i don't wanna take any chances of random disconnects though, so getting the script working would be cool
